function Hd = filterdesigner_01
%FILTERDESIGNER_01 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and DSP System Toolbox 9.16.
% Generated on: 16-Jan-2025 01:27:55

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 44100;  % Sampling Frequency

N   = 4;    % Order
Fc1 = 50;   % First Cutoff Frequency
Fc2 = 500;  % Second Cutoff Frequency

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass('N,F3dB1,F3dB2', N, Fc1, Fc2, Fs)
Hd = design(h, 'butter')

% [EOF]
